### ISSUE TITLE
Jellyfin happen errors with Kodi

### ISSUE THREAD

**Issue by whxciotw** [jellyfin/jellyfin-kodi#112]
**Describe the bug**

Jellyfin addon (0.3.3) happens  terrible error with Kodi, cannot open jellyfin anymore
And works fine with previous version (0.3.2)

**System (please complete the following information):**
 - OS: Android, Windows
 - Jellyfin Version: 10.3.7
 - Kodi Version: 18.4
 - Addon Version: 0.3.3

**Additional context**

**Comment by mcarlton00** [comment]
Possibly related to #108.  0.3.4 should be available later today.  If you'd like to test before it gets officially released, you can install from the master branch using [this file](https://github.com/jellyfin/jellyfin-kodi/archive/master.zip)

**Comment by whxciotw** [comment]
> Possibly related to #108. 0.3.4 should be available later today. If you'd like to test before it gets officially released, you can install from the master branch using [this file](https://github.com/jellyfin/jellyfin-kodi/archive/master.zip)

Yeah, thanks. the problem has been solved after installing this zip file.
And I have disabled the auto-update function, cause this issue spends me nearly 2 hours...

**Comment by dkanada** [comment]
@whxciotw I'm sure @mcarlton00 @oddstr13 and @TrueTechy have spent a lot more than two hours improving this software for **free** to help out users such as yourself...

**Comment by whxciotw** [comment]
> @whxciotw I'm sure @mcarlton00 @oddstr13 and @TrueTechy have spent a lot more than two hours improving this software for **free** to help out users such as yourself...

Yeah,  I believe that too, and thanks a lot for all your contribution

**Comment by dkanada** [comment]
@whxciotw no worries, I know the kodi client doesn't get as much love as the web client but at least it's still getting updates :) we have several clients with no maintainers at all. Hopefully they get picked up by someone eventually.

**Comment by oddstr13** [comment]
#104 probably took me well over 6 hours, but who's counting time anyways..

Fixing this particular issue (which I did a derp and created in the first place) took me maybe 30min, and I actually pushed the fix at the same time as you created this issue.
Then we have mandatory code review to ensure code quality, and actual release with increasing the version number and change log.
This is all done, but the publishing to repo isn't automated quite yet, so all that is left now is for someone with access there to run that part manually.

As for me working on this addon, it's the best way for me to contribute to the project, as I've "always" used Kodi, and Python is my main programming language.

(We're currently slowly loving the Kodi addon to pieces, as we slowly clean up the forked code base;)

**Comment by whxciotw** [comment]
Thanks again and love you all.
Unfortunately I am just a normal user without any programming knowledge, or maybe I can help you.
I noticed 0.3.0 support part of simple Chinese translation, and I can support more Chinese translation in future release if needed.

**Comment by mcarlton00** [comment]
Translations for the project as a whole are mostly handled via Weblate.  Any contributions there are appreciated.

https://translate.jellyfin.org/projects/jellyfin/

**Comment by whxciotw** [comment]
> Translations for the project as a whole are mostly handled via Weblate. Any contributions there are appreciated.
> 
> https://translate.jellyfin.org/projects/jellyfin/

Got it.

**Comment by oddstr13** [comment]
Duplicate of #108
