### ISSUE TITLE
Jellyfin-kodi tries to connect to emby endpoint and fails

### ISSUE THREAD

**Issue by Blackclaws** [jellyfin/jellyfin-kodi#156]
**Describe the bug**
Trying to set up a jellyfin-kodi setup with 0.3.6 on a fresh kodi installation with a fresh 10.4.3 jellyfin-server does not work as expected. It does neither autodiscover the server nor does it connect when manually pointed to it. Autodiscover and connect works with 0.2.1

**To Reproduce**

1. Install jellyfin server
2. Install jellyfin-kodi addon
3. Manually add server
4. See unable to connect

**Expected behavior**
Autodiscover works and manually adding servers works.

**Logs**
2019-12-08 23:15:00.846 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:190 Begin connect
2019-12-08 23:15:00.846 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:84 Begin getAvailableServers
2019-12-08 23:15:01.847 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:402 Found Servers: []
2019-12-08 23:15:01.847 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:91 Found no servers
2019-12-08 23:15:01.847 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:248 Begin connectToServers, with 0 servers
2019-12-08 23:15:12.923 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:276 tryConnect url: http://192.168.178.5/emby/system/info/public
2019-12-08 23:15:14.939 T:18436  NOTICE: Jellyfin.jellyfin.core.http -> ERROR::resources\lib\jellyfin\core\http.py:102 HTTPConnectionPool(host='192.168.178.5', port=80): Max retries exceeded with url: /emby/system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ECAF1FEF60>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
2019-12-08 23:15:14.940 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR::resources\lib\jellyfin\core\connection_manager.py:226 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "resources\lib\jellyfin\core\connection_manager.py", line 224, in _request_url
                                                return self.http.request(request)
                                              File "resources\lib\jellyfin\core\http.py", line 103, in request
                                                self.client.callback("ServerUnreachable", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'
2019-12-08 23:15:14.941 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR::resources\lib\jellyfin\core\connection_manager.py:148 'auth.server-id'
                                            Traceback (most recent call last):
                                              File "resources\lib\jellyfin\core\connection_manager.py", line 146, in connect_to_address
                                                public_info = self._try_connect(address, options=options)
                                              File "resources\lib\jellyfin\core\connection_manager.py", line 284, in _try_connect
                                                'retry': False
                                              File "resources\lib\jellyfin\core\connection_manager.py", line 224, in _request_url
                                                return self.http.request(request)
                                              File "resources\lib\jellyfin\core\http.py", line 103, in request
                                                self.client.callback("ServerUnreachable", {'ServerId': self.config.data['auth.server-id']})
                                            KeyError: 'auth.server-id'
2019-12-08 23:15:14.941 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> ERROR::resources\lib\jellyfin\core\connection_manager.py:142 connectToAddress http://192.168.178.5 failed
2019-12-08 23:15:19.336 T:3388 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2019-12-08 23:15:20.066 T:18436 WARNING: Previous line repeats 50 times.
2019-12-08 23:15:20.066 T:18436  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources\lib\jellyfin\core\connection_manager.py:276 tryConnect url: http://192.168.178.5:8076/emby/system/info/public
2019-12-08 23:15:22.079 T:18436  NOTICE: Jellyfin.jellyfin.core.http -> ERROR::resources\lib\jellyfin\core\http.py:102 HTTPConnectionPool(host='192.168.178.5', port=8076): Max retries exceeded with url: /emby/system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ECAF15A8D0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.3
 - Addon Version: 0.3.6

**Additional context**
I am a bit confused as to why the jellyfin plugin queries the apparently non existing endpoint /emby/system/info/public

**Comment by Blackclaws** [comment]
This is actually an issue with jellyfin-server as it turns out. While the web interface works fine it did not actually start up the required endpoints.

**Comment by albaphysic** [comment]
I'm having the same issue. You resolved it by downgrading jellyfin server? To which version?

**Comment by mcarlton00** [comment]
The `/emby` endpoints are still valid.  They've been depreciated (and will be removed from Kodi soon), but for now they still work.  The likely explanation for these connection issues is the baseurl changes in 10.4.  ie: if you didn't reset your baseurl to `/`, then it's likely that the server is expecting `http://192.168.178.5:8076/jellyfin/emby/system/info/public` or `http://192.168.178.5:8076/jellyfin/system/info/public`.  Either resetting the baseurl in the server or refreshing your Kodi connection with your baseurl on the end should fix it.  Option 2 would see you entering `192.168.178.5:8076/jellyfin` if your baseurl is enabled.

This change occurred during the upgrade from 10.4.0 to 10.4.1, as detailed in the [release notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1)

**Comment by Blackclaws** [comment]
I didn't resolve it by downgrading the server. I resolved it by deleting faulty configuration which blocked parts of the jellyfin api from starting up. In my case it was that upnp was enabled but failed so startup stopped at that stage which was after the web interface but before the endpoints.
