### ISSUE TITLE
Failed to retrieve latest content updates (KodiSyncQueue needs to be re-installed on the server)

### ISSUE THREAD

**Issue by paulmorabito** [jellyfin/jellyfin-kodi#338]
Hi,

I'm running Jellyfin 10.6.0 via docker on a Debian Buster host. On the client, an NVidia Shield TV with Kodi 18.7, I am suddenly getting an error when starting Kodi and just after it connects to Jellyfin:

"Failed to retrieve latest content updates.No content updates will be applied until Kodi is restarted.If this issues persists, please report on the Jellyfin for Kodi forums, with your kodi log".

Log file: [http://paste.kodi.tv/ahozaxogaw](http://paste.kodi.tv/ahozaxogaw)

I tried deleting the local database and re-syncing everything and got the same error afterwards.

EDIT: Just checked dockerhub and the latest tagged image for Jellyfin was updated 2 days ago. This is about the time it began to occur. Perhaps it's linked to this?

Any help would be appreciated!

**Comment by mcarlton00** [comment]
Definitely linked to the update to 10.6.  What likely has happened is that the server side plugin got disabled in the upgrade, and your server has failed to update it for some reason.  That incremental sync on Kodi startup is handled by the Kodi Sync Queue plugin in the server.  Check if you have that installed and that it's version 5.  If not, you'll need to install that again and restart the Jellyfin server.  Things should start syncing properly again after that

**Comment by comrade-meowski** [comment]
I've been following this bug for a couple of days and waiting for a definitive fix to shake free before bothering to fix my clients (manual library updates work ok for a stopgap). I thought this was going to be it but apparently not.

My symptoms are the usual ones: linux host running a recently upgraded to 10.6.0 Jellyfin instance under docker behind a reverse proxy. Main clients are Amazon FireTV sticks running Kodi 18.7 with the latest Jellyfin 0.5.8 plugin.

As it turns out you were completely right and the Kodi Sync Queue plugin was missing from the backend. After installing that and restarting everything the Kodis stopped with the warning message about no content updates but still don't actually sync. The Jellyfin server log has:

```
[2020-07-22 18:23:12.334 +01:00] [INF] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.18.0.3" request
[2020-07-22 18:23:18.154 +01:00] [INF] [58] Jellyfin.Plugin.KodiSyncQueue.API.ServerTimeAPI: Server Time Requested...
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: SyncAPI Created and Listening at "/Jellyfin.Plugin.KodiSyncQueue/{UserID}/GetItems?LastUpdateDT={LastUpdateDT}&format=json" - {LastUpdateDT} must be a UTC DateTime formatted as yyyy-MM-ddTHH:mm:ssZ
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: The following parameters also exist to filter the results:
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: filter=movies,tvshows,music,musicvideos,boxsets
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Results will be included by default and only filtered if added to the filter query...
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: the filter query must be lowercase in both the name and the items...
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Sync Requested for UserID: '"6c88c07389bb4cb498f10619489e53af"' with LastUpdateDT: '"2020-07-22T16:44:38z"'
[2020-07-22 18:23:18.699 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Added: 0, Removed: 0, Updated: 0, Changed User Data: 1
[2020-07-22 18:23:18.699 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Request Finished Taking "00:00:00.0701548"
```
The clients have:

```
020-07-22 18:23:05.325 T:13344  NOTICE: JELLYFIN.__main__ -> INFO::service.py:68 -->[ service ]
2020-07-22 18:23:05.346 T:13344  NOTICE: JELLYFIN.__main__ -> INFO::service.py:69 Delay startup by 0 seconds.
2020-07-22 18:23:07.589 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:62 --->>>[ JELLYFIN ]
2020-07-22 18:23:07.961 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:63 Version: 0.5.8
2020-07-22 18:23:07.994 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:64 KODI Version: 18.7 Git:20200520-f14f7a84e3
2020-07-22 18:23:08.048 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:65 Platform: Linux/Android
2020-07-22 18:23:08.070 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:66 Python Version: 2.7.15 (default, May 20 2020, 10:12:59) 
                                            [GCC 4.2.1 Compatible Android (4751641 based on r328903) Clang 7.0.2 (https://a
2020-07-22 18:23:08.113 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:67 Using dynamic paths: True
2020-07-22 18:23:08.183 T:13420  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:68 Log Level: 1
2020-07-22 18:23:08.314 T:13441  NOTICE: [script.module.clouddrive.common][service-source-1423573480]: Service 'source' started in port 8585
2020-07-22 18:23:08.423 T:13446  NOTICE: [plugin.googledrive][service-player-1257431128]: Service 'player' started.
2020-07-22 18:23:08.424 T:13445  NOTICE: [plugin.googledrive][service-export-1176603096]: Service 'export' started.
2020-07-22 18:23:08.425 T:13443  NOTICE: [plugin.googledrive][service-download-1586600784]: Service 'download' started in port 34719
2020-07-22 18:23:08.467 T:13444  NOTICE: [plugin.googledrive][service-source-1176674808]: Service 'source' started in port 8587
2020-07-22 18:23:08.497 T:13447  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:454 --->[ listener ]
2020-07-22 18:23:08.650 T:13448  NOTICE: JELLYFIN.webservice -> INFO::jellyfin_kodi/webservice.py:46 --->[ webservice/57578 ]
2020-07-22 18:23:08.674 T:13420  NOTICE: JELLYFIN.connect -> INFO::jellyfin_kodi/connect.py:35 --[ server/default ]
2020-07-22 18:23:08.909 T:13420  NOTICE: JELLYFIN -> INFO::jellyfin_kodi/jellyfin/__init__.py:99 ---[ START JELLYFINCLIENT ]---
2020-07-22 18:23:08.974 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:177 Begin connect
2020-07-22 18:23:08.991 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:58 Begin getAvailableServers
2020-07-22 18:23:10.087 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:240 Found Servers: []
2020-07-22 18:23:10.116 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:180 connect has 1 servers
2020-07-22 18:23:10.137 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:155 begin connectToServer
2020-07-22 18:23:10.165 T:13420  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:393 Sending get request to system/info/public
2020-07-22 18:23:10.397 T:13420  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:164 calling onSuccessfulConnection with server failbot-jellyfin
2020-07-22 18:23:10.426 T:13420  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:393 Sending get request to system/info
2020-07-22 18:23:11.085 T:13420  NOTICE: JELLYFIN.jellyfin.client -> INFO::jellyfin_kodi/jellyfin/client.py:58 User is authenticated.
2020-07-22 18:23:11.510 T:13459  NOTICE: JELLYFIN.jellyfin.ws_client -> INFO::jellyfin_kodi/jellyfin/ws_client.py:50 Websocket url: wss://{jellyfin-server}/socket?api_key={jellyfin-token}&device_id=57BDB9CCE42F40519E64FEB9022F6F54
2020-07-22 18:23:11.590 T:13459  NOTICE: JELLYFIN.jellyfin.ws_client -> INFO::jellyfin_kodi/jellyfin/ws_client.py:70 --->[ websocket ]
2020-07-22 18:23:12.148 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:82 --->[ library ]
2020-07-22 18:23:12.165 T:13420  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:302 --[ post capabilities/fbaacc300750491ab7aaa4d88e171728 ]
2020-07-22 18:23:12.372 T:13354  NOTICE: VideoInfoScanner: Starting scan ..
2020-07-22 18:23:12.557 T:13354  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2020-07-22 18:23:12.642 T:13462  NOTICE: JELLYFIN.database -> INFO::jellyfin_kodi/database/__init__.py:175 Database locked in: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database/MyVideos116.db
2020-07-22 18:23:12.924 T:13420  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:46 -->[ kodi scan/video ]
2020-07-22 18:23:12.980 T:13420  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:49 --<[ kodi scan/video ]
2020-07-22 18:23:13.152 T:13462  NOTICE: JELLYFIN.database -> INFO::jellyfin_kodi/database/__init__.py:175 Database locked in: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database/MyMusic72.db
2020-07-22 18:23:17.455 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:379 --[ retrieve changes ] 2020-07-22T16:44:38z
2020-07-22 18:23:17.994 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:546 ---[ userdata:1 ]
2020-07-22 18:23:18.028 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:339 --<[ retrieve changes ]
2020-07-22 18:23:18.073 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:217 -->[ q:download/1257528344 ]
2020-07-22 18:23:19.409 T:13482  NOTICE: JELLYFIN.downloader -> INFO::jellyfin_kodi/downloader.py:329 --<[ q:download/1257528344 ]
2020-07-22 18:23:20.100 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:264 -->[ q:userdata/Episode/1612688424 ]
2020-07-22 18:23:21.417 T:13485  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:689 --<[ q:userdata/1612688424 ]
2020-07-22 18:23:22.217 T:13462  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:440 --[ sync/2020-07-22T17:21:19z ]
2020-07-22 18:23:22.488 T:13329  NOTICE: VideoInfoScanner: Starting scan ..
2020-07-22 18:23:22.535 T:13329  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2020-07-22 18:23:22.605 T:13420  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:46 -->[ kodi scan/video ]
2020-07-22 18:23:22.627 T:13420  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:49 --<[ kodi scan/video ]
2020-07-22 18:24:07.201 T:13490   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/HBO Nordic.png
2020-07-22 18:24:14.354 T:13316  NOTICE: Samba is idle. Closing the remaining connections
```

Are there additional steps that need to be taken? I shall try doing a manual sync first on one of the Kodi clients to see if that has any effect. I'm more than happy to provide full logs or anything else that might help.

**Comment by comrade-meowski** [comment]
A full manual update from one of the Kodi clients completed successfully with the same mixed results I've been having since this issue started: whilst it has added _new_ content that has arrived on the backend since the prior sync it hasn't deleted _old_ content that has been watched and removed from the backend. 

The Jellyfin server log quoth:

```
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: the filter query must be lowercase in both the name and the items...
[2020-07-22 18:23:18.629 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Sync Requested for UserID: '"6c88c07389bb4cb498f10619489e53af"' with LastUpdateDT: '"2020-07-22T16:44:38z"'
[2020-07-22 18:23:18.699 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Added: 0, Removed: 0, Updated: 0, Changed User Data: 1
[2020-07-22 18:23:18.699 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.API.SyncAPI: Request Finished Taking "00:00:00.0701548"
[2020-07-22 18:23:59.358 +01:00] [INF] [22] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2020-07-22 18:24:11.358 +01:00] [INF] [22] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2020-07-22 18:24:23.358 +01:00] [INF] [17] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2020-07-22 18:51:52.182 +01:00] [WRN] [76] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "10.10.10.18". Time (slow): 0:00:00.9027958. "[HOSTNAME REDACTED]/jellyfin/Users/6c88c07389bb4cb498f10619489e53af/Items?IncludeItemTypes=Audio&Recursive=True&LocationTypes=FileSystem%2CRemote%2COffline&Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&CollapseBoxSetItems=False&Limit=1&IsMissing=False&ArtistIds=6dd9409ab5d63227a2bcc518c7dfbbb3&SortOrder=Ascending&EnableTotalRecordCount=True&IsVirtualUnaired=False&SortBy=DateCreated"
[2020-07-22 19:07:20.626 +01:00] [WRN] [80] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:172.18.0.3" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2020-07-22 19:07:20.626 +01:00] [INF] [80] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.18.0.3" closed
```
The client has:

```
2020-07-22 18:45:43.057 T:14107  NOTICE: JELLYFIN.__main__ -> INFO::default.py:39 ---<[ default ]
2020-07-22 18:45:49.770 T:13420  NOTICE: JELLYFIN.full_sync -> INFO::jellyfin_kodi/full_sync.py:57 -->[ fullsync ]
2020-07-22 18:45:50.036 T:13420  NOTICE: JELLYFIN.full_sync -> INFO::jellyfin_kodi/full_sync.py:179 starting sync with [u'1680c99af5bb9ade30ea3d7952fe08c2', u'4514ec850e5ad0c47b58444e17b6346c', u'0859c8c9e00178719def82915bb4a63e', u'868452cb38267695d2ed79e567150065', u'Boxsets:868452cb38267695d2ed79e567150065']
2020-07-22 18:45:50.836 T:13420  NOTICE: JELLYFIN.helper.wrapper -> INFO::jellyfin_kodi/helper/wrapper.py:33 Processing MUM-TV: 1680c99af5bb9ade30ea3d7952fe08c2
2020-07-22 18:45:58.961 T:13420  NOTICE: JELLYFIN.helper.wrapper -> INFO::jellyfin_kodi/helper/wrapper.py:33 Processing TV: 4514ec850e5ad0c47b58444e17b6346c
2020-07-22 18:46:02.995 T:13346  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: wutgf3k5j3hjuncymbh8gg2jo
2020-07-22 18:46:11.199 T:14269   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default/
2020-07-22 18:46:27.700 T:13420  NOTICE: JELLYFIN.helper.wrapper -> INFO::jellyfin_kodi/helper/wrapper.py:33 Processing MUSIC-NG: 0859c8c9e00178719def82915bb4a63e
2020-07-22 18:47:10.847 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 22 missing from kodi. repairing the entry.
2020-07-22 18:47:46.477 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 35 missing from kodi. repairing the entry.
2020-07-22 18:49:51.017 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 83 missing from kodi. repairing the entry.
2020-07-22 18:49:51.621 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 85 missing from kodi. repairing the entry.
2020-07-22 18:49:52.164 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 84 missing from kodi. repairing the entry.
2020-07-22 18:53:26.285 T:13420  NOTICE: JELLYFIN.objects.music -> INFO::jellyfin_kodi/objects/music.py:125 AlbumId 155 missing from kodi. repairing the entry.
2020-07-22 18:53:54.591 T:13420  NOTICE: JELLYFIN.helper.wrapper -> INFO::jellyfin_kodi/helper/wrapper.py:33 Processing FILMS: 868452cb38267695d2ed79e567150065
2020-07-22 18:54:08.201 T:13420  NOTICE: JELLYFIN.helper.wrapper -> INFO::jellyfin_kodi/helper/wrapper.py:36 Processing Gathering boxsets
2020-07-22 18:54:09.427 T:13420  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:440 --[ sync/2020-07-22T17:52:09z ]
2020-07-22 18:54:09.481 T:13420  NOTICE: JELLYFIN.full_sync -> INFO::jellyfin_kodi/full_sync.py:201 Full sync completed in: 0:08:19
2020-07-22 18:54:09.665 T:13420  NOTICE: JELLYFIN.full_sync -> INFO::jellyfin_kodi/full_sync.py:566 --<[ fullsync ]
```

Further information that might be helpful: all my Kodi clients use the Jellyfin plugin exclusively for all TV, Film and Music libraries from the backend. All my Kodi clients also use add-on mode for playback rather than direct.

After a full manual sync and a reboot the Kodi client reconnected and it's log has more of these "Database locked" warnings - significant perhaps?

```
ghost@failbot:/tmp$ cat kodi.log | grep -i locked
2020-07-22 19:12:03.182 T:6207  NOTICE: JELLYFIN.database -> INFO::jellyfin_kodi/database/__init__.py:175 Database locked in: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database/MyVideos116.db
2020-07-22 19:12:03.584 T:6207  NOTICE: JELLYFIN.database -> INFO::jellyfin_kodi/database/__init__.py:175 Database locked in: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database/MyMusic72.db
```

**Comment by mcarlton00** [comment]
I don't remember exactly, but it's possible the last synced date gets changed whether the incremental sync succeeds or not.  Which is bad design, but I didn't think about that until just this moment.  We can try setting that date value to several days ago and see if that causes the items to be processed correctly.

If you can, try modifying `.kodi/userdata/addon_data/plugin.video.jellyfin/sync.json` and changing the 'Date' value to the day before you upgraded the server.  On the next startup sync it _should_ pull all changed items between then and now.

An alternative method that will take longer would be to run a "Repair library" from the addon menu, however this can take a long time as it's essentially a fresh sync.

**Comment by comrade-meowski** [comment]
Thanks for your reply - I think you're right again as I've been prodding a couple of my Kodis while tailing logs and seeing if I could work out what the pattern was. 

It does _seem_ to be the content that arrived in the last X days that is falling through the sync process and not being picked up: completely new content is now showing up correctly and I will shortly find out whether content that arrived either before or after the buggy period disappears as expected when watched/deleted. 

I did trigger manual updates one by one of specific libraries on both instances to see if differences were corrected afterwards and they were - although with a lot of content it's of course difficult to be completely sure that the many hundreds of media files are now accurately synced. 

"Unfortunately" (strange choice of words in this context) the main Kodis I have to hand now are effectively fixed and back in sync but I won't have to look too hard to find more problematic clients as I have several more identical setups dotted about that are going to be showing the same symptoms. I'll try both the "Repair Library" and editing the sync.json date value options on those and report back.

I have noticed that despite having the option enabled in the Jellyfin plugin settings neither of the Kodis I've been fixing have been showing the information bubble pop up with the sync process - purely cosmetic or significant? I do get the "Welcome to Jellyfin" login confirmation pop-up and other general pop-ups on the Kodis though.

**Comment by oddstr13** [comment]
I'm seeing 500 errors reported by the server in the original log file, I'd be interested in seeing the corresponding Jellyfin server log.

**Comment by mcarlton00** [comment]
I'll accept "unfortunately it's fixed" over "it's still broken" any day.

@oddstr13 I'm 90% sure the 500 errors are what it does when Kodi Sync Queue isn't running/installed.  Thinking about it I'd expect a 404 instead, but I haven't looked into that side of the code to know what's happening.

**Comment by paulmorabito** [comment]
@mcarlton00 you were correct, it is missing sync plugin after upgrade. I installed it and it seems to be working again. I'll monitor for issues.

**Comment by dearjoey** [comment]
I have the same issue after upgrade, and how to solve it?

**Comment by dearjoey** [comment]
> I have the same issue after upgrade, and how to solve it?

I reinstall the kodi sync queue plugin, it worked.

**Comment by docfactory37** [comment]
I have the same issue after up dating to 10.6

**Comment by docfactory37** [comment]
Found it was removed after up to 10.6 reinstalled the pouting and all fine now.

**Comment by mcarlton00** [comment]
Been long enough since 10.6 was released, this can be closed now
